# Generated by Django 4.2.5 on 2023-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustRegst',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
