# Generated by Django 4.2.5 on 2023-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custregpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custregst',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
