# Generated by Django 4.2.5 on 2023-09-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custregpg', '0002_alter_custregst_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custregst',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='custregst',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='custregst',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='custregst',
            old_name='mname',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='custregst',
            old_name='uname',
            new_name='user_name',
        ),
    ]
